server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch interval-seconds: 5
    healthcheck:
      enable: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
